"""Constantes equivalentes a Config.h del proyecto C++ original."""

PROCESSING_FPS_STAT_QUEUE_LENGTH = 32
CAPTURE_FPS_STAT_QUEUE_LENGTH = 32

DEFAULT_IMAGE_BUFFER_SIZE = 1
DEFAULT_DROP_FRAMES = False

DEFAULT_COL_MAG_LEVELS = 3
DEFAULT_LAP_MAG_EXAGGERATION = 2.0
DEFAULT_LAP_MAG_LEVELS = 4

DEFAULT_GRAYSCALE = False
DEFAULT_MAGNIFY_TYPE = 0

DEFAULT_CM_AMPLIFICATION = 100
DEFAULT_CM_COWAVELENGTH = 1000
DEFAULT_CM_COLOW = 0.84
DEFAULT_CM_COHIGH = 1.43
DEFAULT_CM_CHROMATTENUATION = 0

DEFAULT_MM_AMPLIFICATION = 20
DEFAULT_MM_COWAVELENGTH = 50
DEFAULT_MM_COLOW = 20.0
DEFAULT_MM_COHIGH = 40.0
DEFAULT_MM_CHROMATTENUATION = 0

DEFAULT_PB_AMPLIFICATION = 25
DEFAULT_PB_COWAVELENGTH = 25
DEFAULT_PB_COLOW = 0.1
DEFAULT_PB_COHIGH = 1.0

# ROI en el visor: tamaño mínimo en píxeles del frame fuente (pirámides / OpenCV).
MIN_ROI_SIDE = 96
